#  ============LICENSE_START=======================================================
#  Modification (C) 2021 Nordix Foundation
#  ================================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#  ============LICENSE_END=========================================================

server:
  port: 8080

rest:
  api:
    dmi-base-path: /dmi/api

security:
  permit-uri: /manage/health/**,/manage/info,/swagger-ui/**,/swagger-resources/**,/v3/api-docs
  auth:
    username: ${CPS_USERNAME:cps}
    password: ${CPS_PASSWORD:cps}

# Actuator
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: info,health,loggers
  endpoint:
    health:
      show-details: always
      # kubernetes probes: liveness and readiness
      probes:
        enabled: true
    loggers:
      enabled: true

cps-core:
  baseUrl: http://${CPS_CORE_HOST:localhost}:${CPS_CORE_PORT:8080}
  auth:
    username: ${CPS_CORE_USERNAME:cps}
    password: ${CPS_CORE_PASSWORD:cps}

logging:
  level:
    org.springframework: ERROR
    org.onap.cps: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: dmi.log
